version: '3.9'

services:
  app:
    build: 
      context: .
    volumes:
      -static-data:/vol/web
    environment:
     # - SECRET_KEY=8#z(!va8x+l%+ivg-m-kd!y5$&#_^#lqlr4#!xkt%e)1n3li8+
      - ALLOWED_HOST=hamincharkho.pw, www.hamincharkho.pw
  
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      -8080:8080
    depends_on:
      - app

volumes:
  static_data: